name = "Bites"
uuid = "2f663d54-bd46-4a48-a0cb-d4db94f332c6"
authors = ["John Palmer <johnrbpalmer@gmail.com> and contributors"]
version = "0.1.6"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10"
Distributions = "0.25"
Plots = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
